version: '3.8'
services:
  backend:
    build: 
      context: .  # Replace with your actual directory path
    container_name: backend
    depends_on: mongo
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      -MONGODB_URI=mongodb://localhost:27017/test
   
  mongo:
    image: mongo
    container_name: app_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: